# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Default configuration for use with tic package
# Usually you shouldn't need to change the first part of the file

# DO NOT CHANGE THE CODE BELOW
before_install: R -q -e 'install.packages(c("remotes", "curl")); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); tic::before_install()'
install: R -q -e 'tic::install()'
after_install: R -q -e 'tic::after_install()'
before_script: R -q -e 'tic::before_script()'
script: R -q -e 'tic::script()'
after_success: R -q -e 'tic::after_success()'
after_failure: R -q -e 'tic::after_failure()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
after_deploy: R -q -e 'tic::after_deploy()'
after_script: R -q -e 'tic::after_script()'
# DO NOT CHANGE THE CODE ABOVE

# Custom parts:

# Header
language: r
sudo: false
dist: trusty
cache: packages
latex: false
fortran: false

#stages: test, full
stages:
- name: test
  if: branch != docs
- name: docs
  if: branch = docs OR branch = master
- name: full
  if: branch = master

#jobs
matrix:
  include:
  - r: devel
    env:
    - DEV_VERSIONS=true
  - r: 3.3
  - stage: docs
    r: release
    env:
    - BUILD_PKGDOWN=true
  - stage: full
    os: osx
  - r: 3.5
  - r: 3.4
  allow_failures:
  - r: devel
    env:
    - DEV_VERSIONS=TRUE
  fast_finish: true

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - _R_CHECK_SYSTEM_CLOCK_=false
  - MAKEFLAGS="-j 2"

#notifications
notifications:
  email:
    on_success: change
    on_failure: change

# Custom parts:

#services
services:
